### ISSUE TITLE
Direct link to GPlay Music from Google Store link

### ISSUE THREAD

**Issue by mylesagray** [suivethefirst/spotitunes#3]
Auto jump to google play music link based on ID in store URL:

https://play.google.com/store/music/album/Deathlike_Silence_Saturday_Night_Evil?id=Bn4ucvsmwchsuabesh6sl7jc5fu

GPlay link for same:

https://play.google.com/music/listen?view=Bn4ucvsmwchsuabesh6sl7jc5fu_cid&authuser=0

**Comment by suivethefirst** [comment]
Changed the link to be formed as above. We're assuming that a play link will always have the trailing "_cid&authuser=0"

**Comment by suivethefirst** [comment]
Confirmed working.
