### ISSUE TITLE
Same behaviour for iTunes and Google Music links that are posted.

### ISSUE THREAD

**Issue by mylesagray** [suivethefirst/spotitunes#5]
iTunes and GMusic links that are posted should translate into spotify, gmusic and itunes, spotify respectively

**Comment by suivethefirst** [comment]
itunessource branch is WIP on this. Requires some extension around the data returned by the parsing function and the handling of this by the main routine.

**Comment by suivethefirst** [comment]
Merged the itunessource branch and pushed to Heroku. This should cover iTunes link. Might have to take a look at GMusic some other time if they publish an API...
