### ISSUE TITLE
Handle Google Music links

### ISSUE THREAD

**Issue by suivethefirst** [suivethefirst/spotitunes#8]

**Comment by suivethefirst** [comment]
@MylesGray New issue to focus on Google Music links.

**Comment by mylesagray** [comment]
Album name and Artist can be pulled from source URL: 

`https://play.google.com/music/listen?u=0#/album/Ba5nzc4nq5eg554uspfkyh6ax6m/Rodrigo+y+Gabriela/Live+In+France`

`+` correlates to spaces

Any ASCII characters use standard encoding:

`https://play.google.com/music/listen?u=0#/album/B43ebdvkhrrzbv6bfmuhah3wbsu/Rodrigo+y+Gabriela/11%3A11`

Album name of the above is `11:11`

First Artist then Album

**Comment by mylesagray** [comment]
Fixed in latest commit.
