### ISSUE TITLE
Add Google Music "Share" link for parsing

### ISSUE THREAD

**Issue by mylesagray** [suivethefirst/spotitunes#9]
`https://play.google.com/music/m/Bumc4n5cjpwchxo6agsvbmb3lqu?t=The_Blackening_-_Machine_Head`

**Comment by suivethefirst** [comment]
Once this is added it might be worth adding a note to the message output when people submit the link with authentication required that they should use the share link.

**Comment by mylesagray** [comment]
Probably be good if we can do a slackbot type "only you can see this" message?
